/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/pc-projects-otimizado.glb -d 
Author: darekagomi (https://sketchfab.com/darekagomi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pc-9801ux-2befdff3817c4b1f86373149f3328e2f
Title: PC-9801UX
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pc-projects-otimizado.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.cable_PC9801U001_0.geometry}
        material={materials['PC9801U.001']}
        position={[96.526, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={11.269}
      />
      <mesh
        geometry={nodes['FD1_���������������007_0'].geometry}
        material={materials.PaletteMaterial001}
        position={[35.38, 21.57, -6.869]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[100, 100, 98]}
      />
      <mesh
        geometry={nodes['FD1_���������������006_0'].geometry}
        material={materials.PaletteMaterial002}
        position={[35.38, 21.57, -6.869]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[100, 100, 98]}
      />
      <mesh
        geometry={nodes['0'].geometry}
        material={materials.Material}
        position={[10.349, 86.658, -27.724]}
        rotation={[-Math.PI / 2, 0, 0]} scale={100}
      />
      <mesh
        geometry={nodes['2'].geometry}
        material={materials.PaletteMaterial003}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes['1'].geometry}
        material={materials['PC9801UX.001']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.PCKD854n_PCKD854n001_0.geometry}
        material={materials['PCKD854n.001']}
        position={[-0.077, 75.996, -33.893]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload('/pc-projects-otimizado.glb')
