/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: darekagomi (https://sketchfab.com/darekagomi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pc-9801ux-2befdff3817c4b1f86373149f3328e2f
Title: PC-9801UX
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useVideoTexture } from '@react-three/drei'
import * as THREE from 'three'
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';

const DemoComputer = (props) => {
  const group = useRef();
  const { nodes, materials } = useGLTF('models/pc-projects-otimizado.glb');
  
  const txt = useVideoTexture(props.texture || '/textures/project/SGES.mp4');

  useEffect(() => {
    const geo = nodes['0']?.geometry;
    if (!geo || !geo.attributes.uv) return;

    const uvAttr = geo.attributes.uv;
    let minU = Infinity, maxU = -Infinity;
    let minV = Infinity, maxV = -Infinity;

    for (let i = 0; i < uvAttr.count; i++) {
      const u = uvAttr.getX(i);
      const v = uvAttr.getY(i);
      if (u < minU) minU = u;
      if (u > maxU) maxU = u;
      if (v < minV) minV = v;
      if (v > maxV) maxV = v;
    }

    const rangeU = maxU - minU || 1;
    const rangeV = maxV - minV || 1;

    for (let i = 0; i < uvAttr.count; i++) {
      uvAttr.setX(i, (uvAttr.getX(i) - minU) / rangeU);
      uvAttr.setY(i, (uvAttr.getY(i) - minV) / rangeV);
    }
    uvAttr.needsUpdate = true;
  }, [nodes]);

  useEffect(() => {
    if (!txt) return;
    txt.wrapS = THREE.ClampToEdgeWrapping;
    txt.wrapT = THREE.ClampToEdgeWrapping;
    txt.center.set(0.5, 0.5);
    txt.rotation = -Math.PI / 2;
    txt.repeat.set(1, 1);
    txt.offset.set(0, 0);
    // Melhora a nitidez da textura de vídeo
    txt.minFilter = THREE.LinearFilter;
    txt.magFilter = THREE.LinearFilter;
    txt.generateMipmaps = false;
    txt.anisotropy = 16;
    txt.needsUpdate = true;
  }, [txt]);
  
  useGSAP(() => {
    gsap.from(group.current.rotation, {
      y: Math.PI / 2,
      duration: 1,
      ease: 'power3.out',
    });
  }, [txt]);
  
  return (
    <group ref={group} {...props} dispose={null}>
      {nodes['FD1_007_0'] && (
        <group
          name='Pc-disquete1'
          position={[35.38, 21.57, -6.869]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[100, 100, 98]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['FD1_007_0'].geometry}
            material={materials.PaletteMaterial001 || materials['.007']}
          />
          {nodes['FD1_006_0'] && (
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['FD1_006_0'].geometry}
              material={materials.PaletteMaterial002 || materials['.006']}
            />
          )}
        </group>
      )}
      <group
        name='CPU'
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}>
        {nodes['2'] && (
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['2'].geometry}
            material={materials.PaletteMaterial003 || materials['Lamp.001']}
          />
        )}
        {nodes['1'] && (
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['1'].geometry}
            material={materials['PC9801UX.001']}
          />
        )}
      </group>
      <group 
        name='Monitor'
        position={[-0.077, 75.996, -33.893]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={120}>
        {nodes.PCKD854n_PCKD854n001_0 && (
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PCKD854n_PCKD854n001_0.geometry}
            material={materials['PCKD854n.001']}
          />
        )}
      </group>
      {nodes.cable_PC9801U001_0 && (
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cable_PC9801U001_0.geometry}
          material={materials['PC9801U.001']}
          position={[96.526, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={11.269}
        />
      )}
      {nodes['0'] && (
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['0'].geometry}
          position={[10.3, 90, -20.5]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[133.2, 115.7, 124.8]}
        >
          <meshBasicMaterial map={txt} />
        </mesh>
      )}
    </group>
  )
}

useGLTF.preload('models/pc-projects-otimizado.glb')
export default DemoComputer;
