/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: darekagomi (https://sketchfab.com/darekagomi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pc-9801ux-2befdff3817c4b1f86373149f3328e2f
Title: PC-9801UX
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const DemoComputer = (props) => {
  const { nodes, materials } = useGLTF('/models/pc-projects.glb')
  return (
    <group {...props} dispose={null}>
      <group
        position={[35.38, 21.57, -6.869]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[100, 100, 98]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['FD1_���������������007_0'].geometry}
          material={materials['.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['FD1_���������������006_0'].geometry}
          material={materials['.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['FD1_���������������005_0'].geometry}
          material={materials['.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['FD1_���������������004_0'].geometry}
          material={materials['.004']}
        />
      </group>
      <group
        position={[35.38, 15.236, -6.869]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[100, 100, 98]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['FD2_���������������007_0'].geometry}
          material={materials['.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['FD2_���������������006_0'].geometry}
          material={materials['.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['FD2_���������������005_0'].geometry}
          material={materials['.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['FD2_���������������004_0'].geometry}
          material={materials['.004']}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['2'].geometry}
          material={materials['Lamp.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['1'].geometry}
          material={materials['PC9801UX.001']}
        />
      </group>
      <group position={[-0.077, 75.996, -33.893]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PCKD854n_PCKD854n001_0.geometry}
          material={materials['PCKD854n.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PCKD854n_Lamp001_0.geometry}
          material={materials['Lamp.001']}
        />
      </group>
      <group
        position={[85.791, 0, 48.96]}
        rotation={[-Math.PI / 2, 0, -0.436]}
        scale={[100, 100, 98]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['FD3_���������������007_0'].geometry}
          material={materials['.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['FD3_���������������006_0'].geometry}
          material={materials['.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['FD3_���������������005_0'].geometry}
          material={materials['.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['FD3_���������������004_0'].geometry}
          material={materials['.004']}
        />
      </group>
      <group
        position={[108.829, 0, 72.691]}
        rotation={[Math.PI / 2, 0, -3.054]}
        scale={[100, 100, 98]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['FD4_���������������007_0'].geometry}
          material={materials['.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['FD4_���������������006_0'].geometry}
          material={materials['.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['FD4_���������������005_0'].geometry}
          material={materials['.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['FD4_���������������004_0'].geometry}
          material={materials['.004']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cable_PC9801U001_0.geometry}
        material={materials['PC9801U.001']}
        position={[96.526, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={11.269}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['0'].geometry}
        material={materials.Material}
        position={[10.349, 86.658, -27.724]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PC9801U_PC9801U001_0.geometry}
        material={materials['PC9801U.001']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload('/models/pc-projects.glb')
export default DemoComputer;
