/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: adibfuadimuhammad (https://sketchfab.com/adibfuadimuhammad)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laravel-51175376880b4f86902919fcaf8b246a
Title: laravel
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

const LaravelLogo = (props) => {
  const { nodes, materials } = useGLTF('/models/laravel.glb')
  return (
    <Float dispose={null} floatIntensity={1} floatingRange={0.5}>
      <group {...props}>
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials['SVGMat.003']}
          position={[0.00191, 0.122762, 0.160157]}
          rotation={[0, 0, 1.80155]}
        /> */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials['SVGMat.001']}
          position={[0.042205, 0.147725, 0.163812]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.29131}
        />
      </group>
    </Float>
  )
}

useGLTF.preload('/models/laravel.glb')
export default LaravelLogo;

