/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
Title: React logo
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

const ReactLogo = (props) => {
  const { nodes, materials } = useGLTF('/public/models/react.glb')
  return (
    <Float>
      <group {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['React-Logo_Material002_0'].geometry}
          material={materials['Material.002']}
          // position={[0, 7.9355, 18.101]}
          position={[0, 0.079355, 0.181016]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[3.9166, 3.9166, 6.2734]}
        />
      </group>
    </Float>
  )
}

useGLTF.preload('/public/models/react.glb')

export default ReactLogo;