/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AyoubBani (https://sketchfab.com/AyoubBani)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/game-bar-target-arrow-03e07087107944f8957571f8ce4bcaa4
Title: Game Bar Target Arrow
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';

const Target = (props) => {
  const targetRef = useRef();
  const { nodes, materials } = useGLTF('/public/models/target-otimizado.glb');
  
  useGSAP( () => {
    gsap.to(targetRef.current.position, {
      y: targetRef.current.position.y + 0.5,
      duration: 1.25,
      repeat: -1,
      yoyo: true
    })
    
  });
  
  return (  
    <group {...props} ref={targetRef} dispose={null}>
      <group scale={0.01}>
        <group
          position={[7.224, 0, 0]}
          rotation={[-Math.PI / 2, 0, 5]}
          scale={25}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_arrow_red_0.geometry}
            material={materials.arrow_red}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_target_white_0.geometry}
            material={materials.target_white}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/public/models/target-otimizado.glb');
export default Target;